# Generated by Django 4.2.3 on 2023-08-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategMatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unidade', models.CharField(choices=[('MT', 'METRO'), ('PÇ', 'PEÇA')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mat_prima.categmatprima')),
            ],
        ),
    ]
